#!/usr/bin/env tsx
/**
 * Canadian Law MCP — Ingestion Pipeline
 *
 * Fetches Canadian federal legislation from Justice Laws Website (laws-lois.justice.gc.ca).
 * Downloads the FullText.html page for each Act and parses the structured HTML
 * into provision-level JSON seed files.
 *
 * **Census-driven**: Reads data/census.json (generated by scripts/census.ts) to
 * enumerate ALL federal Acts. Falls back to KEY_CANADIAN_ACTS if census is missing.
 *
 * Usage:
 *   npm run ingest                    # Full ingestion (from census)
 *   npm run ingest -- --limit 5       # Test with 5 acts
 *   npm run ingest -- --skip-fetch    # Reuse cached pages
 *   npm run ingest -- --resume        # Skip acts that already have seed files
 *
 * Data is sourced under the Open Government Licence - Canada.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { fetchActFullText } from './lib/fetcher.js';
import { parseFullTextHtml, KEY_CANADIAN_ACTS, type ActIndexEntry, type ParsedAct } from './lib/parser.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SOURCE_DIR = path.resolve(__dirname, '../data/source');
const SEED_DIR = path.resolve(__dirname, '../data/seed');
const CENSUS_PATH = path.resolve(__dirname, '../data/census.json');

interface CensusAct {
  id: string;
  actPath: string;
  title: string;
  citation: string;
  url: string;
  classification: 'ingestable' | 'inaccessible' | 'metadata_only';
}

interface CensusData {
  generated_at: string;
  stats: { total: number; class_ingestable: number; class_inaccessible: number; class_metadata_only: number };
  laws: CensusAct[];
}

function parseArgs(): { limit: number | null; skipFetch: boolean; resume: boolean } {
  const args = process.argv.slice(2);
  let limit: number | null = null;
  let skipFetch = false;
  let resume = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--limit' && args[i + 1]) {
      limit = parseInt(args[i + 1], 10);
      i++;
    } else if (args[i] === '--skip-fetch') {
      skipFetch = true;
    } else if (args[i] === '--resume') {
      resume = true;
    }
  }

  return { limit, skipFetch, resume };
}

/**
 * Convert a census act entry into the ActIndexEntry format used by the parser.
 */
function censusActToIndexEntry(censusAct: CensusAct): ActIndexEntry {
  // Generate a short name from the title (first 30 chars or well-known abbreviation)
  const shortName = censusAct.title.length > 40
    ? censusAct.title.substring(0, 37) + '...'
    : censusAct.title;

  return {
    id: censusAct.id,
    actPath: censusAct.actPath,
    title: censusAct.title,
    titleFr: '',  // Not available from census index
    shortName,
    status: 'in_force',
    issuedDate: '',
    inForceDate: '',
    url: censusAct.url,
  };
}

/**
 * Load acts from census.json if available, otherwise fall back to KEY_CANADIAN_ACTS.
 */
function loadActList(): ActIndexEntry[] {
  if (fs.existsSync(CENSUS_PATH)) {
    const raw = fs.readFileSync(CENSUS_PATH, 'utf-8');
    const census = JSON.parse(raw) as CensusData;

    console.log(`  Census: ${census.stats.total} Acts (generated ${census.generated_at})`);

    // Only include ingestable acts
    const ingestable = census.laws.filter(a => a.classification === 'ingestable');
    console.log(`  Ingestable: ${ingestable.length} Acts`);

    return ingestable.map(censusActToIndexEntry);
  }

  console.log('  WARNING: No census.json found — falling back to KEY_CANADIAN_ACTS (9 acts)');
  console.log('  Run: npx tsx scripts/census.ts   to generate full census\n');
  return KEY_CANADIAN_ACTS;
}

async function fetchAndParseActs(acts: ActIndexEntry[], skipFetch: boolean, resume: boolean): Promise<void> {
  console.log(`\nProcessing ${acts.length} federal Acts...\n`);

  fs.mkdirSync(SOURCE_DIR, { recursive: true });
  fs.mkdirSync(SEED_DIR, { recursive: true });

  let processed = 0;
  let skipped = 0;
  let resumed = 0;
  let failed = 0;
  let softFourOhFour = 0;
  let totalProvisions = 0;
  let totalDefinitions = 0;
  const startTime = Date.now();

  const report: { act: string; provisions: number; definitions: number; status: string }[] = [];

  for (const act of acts) {
    const sourceFile = path.join(SOURCE_DIR, `${act.id}.html`);
    const seedFile = path.join(SEED_DIR, `${act.id}.json`);

    // Resume support: skip acts that already have seed files
    if (resume && fs.existsSync(seedFile)) {
      const existing = JSON.parse(fs.readFileSync(seedFile, 'utf-8')) as ParsedAct;
      totalProvisions += existing.provisions.length;
      totalDefinitions += existing.definitions.length;
      resumed++;
      processed++;
      continue;
    }

    // Skip if seed already exists and we're in skip-fetch mode
    if (skipFetch && fs.existsSync(seedFile)) {
      const existing = JSON.parse(fs.readFileSync(seedFile, 'utf-8')) as ParsedAct;
      report.push({
        act: act.shortName,
        provisions: existing.provisions.length,
        definitions: existing.definitions.length,
        status: 'cached',
      });
      totalProvisions += existing.provisions.length;
      totalDefinitions += existing.definitions.length;
      skipped++;
      processed++;
      continue;
    }

    try {
      let html: string;

      if (fs.existsSync(sourceFile) && skipFetch) {
        html = fs.readFileSync(sourceFile, 'utf-8');
        console.log(`  Using cached ${act.shortName} (${act.actPath})`);
      } else {
        process.stdout.write(`  [${processed + 1}/${acts.length}] Fetching ${act.actPath}...`);
        const result = await fetchActFullText(act.actPath);

        if (result.status !== 200) {
          console.log(` HTTP ${result.status} -- SKIPPED`);
          report.push({ act: act.shortName, provisions: 0, definitions: 0, status: `HTTP ${result.status}` });
          failed++;
          processed++;
          continue;
        }

        // Check if we got the 404 error page (server returns 200 for soft 404s)
        if (result.body.includes('Page not Found') || result.body.includes('Error 404')) {
          console.log(` SOFT 404 -- SKIPPED`);
          report.push({ act: act.shortName, provisions: 0, definitions: 0, status: 'soft 404' });
          softFourOhFour++;
          failed++;
          processed++;
          continue;
        }

        html = result.body;
        fs.writeFileSync(sourceFile, html);
        console.log(` OK (${(html.length / 1024).toFixed(0)} KB)`);
      }

      const parsed = parseFullTextHtml(html, act);
      fs.writeFileSync(seedFile, JSON.stringify(parsed, null, 2));

      totalProvisions += parsed.provisions.length;
      totalDefinitions += parsed.definitions.length;

      report.push({
        act: act.shortName,
        provisions: parsed.provisions.length,
        definitions: parsed.definitions.length,
        status: 'OK',
      });

      console.log(`    -> ${parsed.provisions.length} provisions, ${parsed.definitions.length} definitions`);
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      console.log(`  ERROR parsing ${act.shortName}: ${msg}`);
      report.push({ act: act.shortName, provisions: 0, definitions: 0, status: `ERROR: ${msg}` });
      failed++;
    }

    processed++;

    // Progress log every 25 acts
    if (processed % 25 === 0) {
      const elapsed = ((Date.now() - startTime) / 1000).toFixed(0);
      const eta = ((Date.now() - startTime) / processed * (acts.length - processed) / 1000).toFixed(0);
      console.log(`\n  --- Progress: ${processed}/${acts.length} (${elapsed}s elapsed, ~${eta}s remaining) ---\n`);
    }
  }

  const totalElapsed = ((Date.now() - startTime) / 1000).toFixed(1);

  // Print summary report (only show non-resumed acts in detail)
  console.log(`\n${'='.repeat(70)}`);
  console.log('INGESTION REPORT');
  console.log('='.repeat(70));

  if (report.length <= 100) {
    console.log(`${'Act'.padEnd(40)} ${'Prov'.padEnd(8)} ${'Defs'.padEnd(8)} Status`);
    console.log('-'.repeat(70));
    for (const r of report) {
      console.log(
        `${r.act.substring(0, 39).padEnd(40)} ${String(r.provisions).padEnd(8)} ${String(r.definitions).padEnd(8)} ${r.status}`
      );
    }
    console.log('-'.repeat(70));
  } else {
    // For large runs, just show the summary stats
    const okCount = report.filter(r => r.status === 'OK').length;
    const failedCount = report.filter(r => r.status !== 'OK' && r.status !== 'cached').length;
    const cachedCount = report.filter(r => r.status === 'cached').length;
    console.log(`  New ingestions:  ${okCount}`);
    console.log(`  Cached:          ${cachedCount}`);
    console.log(`  Failed:          ${failedCount}`);
    if (failedCount > 0) {
      console.log('\n  Failed acts:');
      for (const r of report.filter(r => r.status !== 'OK' && r.status !== 'cached')) {
        console.log(`    ${r.act.substring(0, 39).padEnd(40)} ${r.status}`);
      }
    }
  }

  console.log(`\n${'='.repeat(70)}`);
  console.log(`  Total elapsed:     ${totalElapsed}s`);
  console.log(`  Acts processed:    ${processed}`);
  console.log(`  Acts resumed:      ${resumed}`);
  console.log(`  Acts cached:       ${skipped}`);
  console.log(`  Acts failed:       ${failed}`);
  console.log(`  Soft 404s:         ${softFourOhFour}`);
  console.log(`  Total provisions:  ${totalProvisions}`);
  console.log(`  Total definitions: ${totalDefinitions}`);

  // Update census.json with ingestion stats
  if (fs.existsSync(CENSUS_PATH)) {
    const census = JSON.parse(fs.readFileSync(CENSUS_PATH, 'utf-8'));
    census.ingestion = {
      completed_at: new Date().toISOString(),
      total_laws: processed - failed,
      total_provisions: totalProvisions,
      coverage_pct: ((processed - failed) / acts.length * 100).toFixed(1),
    };

    // Update classification for soft 404 acts
    if (softFourOhFour > 0) {
      const failedReport = report.filter(r => r.status === 'soft 404');
      for (const fr of failedReport) {
        const censusAct = census.laws.find((a: CensusAct) => a.title.startsWith(fr.act.substring(0, 30)));
        if (censusAct) {
          censusAct.classification = 'inaccessible';
        }
      }
      census.stats.class_ingestable = census.laws.filter((a: CensusAct) => a.classification === 'ingestable').length;
      census.stats.class_inaccessible = census.laws.filter((a: CensusAct) => a.classification === 'inaccessible').length;
    }

    fs.writeFileSync(CENSUS_PATH, JSON.stringify(census, null, 2) + '\n');
    console.log(`\n  Updated census.json with ingestion stats.`);
  }
}

async function main(): Promise<void> {
  const { limit, skipFetch, resume } = parseArgs();

  console.log('Canadian Law MCP -- Ingestion Pipeline');
  console.log('======================================\n');
  console.log(`  Source:  Justice Laws Website (laws-lois.justice.gc.ca)`);
  console.log(`  Method:  FullText.html (structured HTML)`);
  console.log(`  License: Open Government Licence - Canada`);

  if (limit) console.log(`  --limit ${limit}`);
  if (skipFetch) console.log(`  --skip-fetch`);
  if (resume) console.log(`  --resume (skip existing seed files)`);

  const allActs = loadActList();
  const acts = limit ? allActs.slice(0, limit) : allActs;
  await fetchAndParseActs(acts, skipFetch, resume);
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
